# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 931401a1613a4c0300889a286101f065084f4ceddf778fd3b1e2eb4e9cf09f950a6134ee40291e4b020d5ede164d4accd2ed9121e0936fe811434cf658628b63

test:
  secret_key_base: 32ae9f716693a35721d0d134b49827999d1473b19670fae43f68ce7cfe0baf6d5123d161708886634521dffc56dcd2d925f1a0b382bd2321b9237d4a98f98797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
